"""Curated Reddit-style sample corpus for offline showcase runs.

Each row is paraphrased from recurring public discourse patterns in
legal-tech subreddits. Used when Reddit API credentials are unavailable.
"""

from datetime import datetime, timezone

COLLECTED_AT = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

SAMPLE_REDDIT_POSTS = [
    {
        "id": "reddit_001",
        "subreddit": "lawyers",
        "title": "Anyone actually trusting ChatGPT for research after Mata?",
        "body_text": "I'm a solo and tried ChatGPT for a motion outline. It cited cases that looked real but were completely fabricated. After Mata I feel like I need to verify every sentence. Curious what others use that is actually grounded in real citations.",
        "author": "solo_litigator",
        "score": 412,
        "num_comments": 89,
        "created_date": "2024-03-15",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_chatgpt_trust/",
        "post_type": "post",
    },
    {
        "id": "reddit_002",
        "subreddit": "lawyers",
        "title": "",
        "body_text": "We piloted Harvey for contract review. Accuracy is better than generic chatbots but I still catch wrong clause summaries weekly. The value is speed on first pass, not final judgment. You must validate everything before it goes to a client.",
        "author": "biglaw_associate",
        "score": 156,
        "num_comments": 0,
        "created_date": "2024-06-02",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_chatgpt_trust/",
        "post_type": "comment",
    },
    {
        "id": "reddit_003",
        "subreddit": "LegalTech",
        "title": "Harvey vs CoCounsel for mid-size litigation shop?",
        "body_text": "Managing partner wants us to pick one AI stack this quarter. Harvey demo was impressive but pricing is opaque. CoCounsel integrates with Westlaw which our associates already live in. Worried about subscription creep when you add research plus AI tiers.",
        "author": "lit_support_lead",
        "score": 98,
        "num_comments": 44,
        "created_date": "2025-01-10",
        "source_url": "https://www.reddit.com/r/LegalTech/comments/sample_harvey_cocounsel/",
        "post_type": "post",
    },
    {
        "id": "reddit_004",
        "subreddit": "LegalTech",
        "title": "",
        "body_text": "Our firm pays roughly 400 per user per month once you stack research and AI. ROI only works if partners actually change workflow and stop re-billing manual review hours.",
        "author": "ops_director",
        "score": 67,
        "num_comments": 0,
        "created_date": "2025-01-11",
        "source_url": "https://www.reddit.com/r/LegalTech/comments/sample_harvey_cocounsel/",
        "post_type": "comment",
    },
    {
        "id": "reddit_005",
        "subreddit": "LawFirm",
        "title": "Partners still refuse to adopt any AI tools",
        "body_text": "I'm at a 40 attorney firm. Younger associates use ChatGPT quietly. Partners say malpractice risk and client confidentiality. We have no firm AI policy. Perfect is the enemy of good but nobody wants to be the test case.",
        "author": "associate_year3",
        "score": 234,
        "num_comments": 71,
        "created_date": "2024-11-20",
        "source_url": "https://www.reddit.com/r/LawFirm/comments/sample_adoption_resistance/",
        "post_type": "post",
    },
    {
        "id": "reddit_006",
        "subreddit": "LawFirm",
        "title": "",
        "body_text": "Billable hour model is the real barrier. If AI saves ten hours on discovery review, who captures that efficiency? Until compensation changes, adoption will stay secret and uneven.",
        "author": "senior_associate",
        "score": 189,
        "num_comments": 0,
        "created_date": "2024-11-21",
        "source_url": "https://www.reddit.com/r/LawFirm/comments/sample_adoption_resistance/",
        "post_type": "comment",
    },
    {
        "id": "reddit_007",
        "subreddit": "lawyers",
        "title": "AI saved me 6 hours on a discovery privilege log draft",
        "body_text": "Used our ediscovery platform AI assist on a document review batch. Still made every privilege call myself but first-pass clustering cut review time dramatically. Not magic, just faster triage. Would not trust it on nuanced privilege without human eyes.",
        "author": "discovery_attorney",
        "score": 301,
        "num_comments": 52,
        "created_date": "2025-02-08",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_ediscovery_efficiency/",
        "post_type": "post",
    },
    {
        "id": "reddit_008",
        "subreddit": "LegalTech",
        "title": "Relativity aiR for review — honest experience?",
        "body_text": "Has anyone deployed aiR on a real matter? We need transparent and defensible TAR workflows. Courts accept AI assisted review if you document the process. Looking for practical gotchas not vendor slides.",
        "author": "ediscovery_pm",
        "score": 45,
        "num_comments": 19,
        "created_date": "2024-09-14",
        "source_url": "https://www.reddit.com/r/LegalTech/comments/sample_relativity_air/",
        "post_type": "post",
    },
    {
        "id": "reddit_009",
        "subreddit": "ChatGPT",
        "title": "Lawyer here — stop using ChatGPT for case citations",
        "body_text": "Every week someone posts about getting burned by fake cases. LLMs are probabilistic text generators not legal databases. Use purpose-built legal research tools or you are asking for sanctions. Human verification is mandatory.",
        "author": "ethics_nerd",
        "score": 892,
        "num_comments": 143,
        "created_date": "2023-06-12",
        "source_url": "https://www.reddit.com/r/ChatGPT/comments/sample_lawyer_warning/",
        "post_type": "post",
    },
    {
        "id": "reddit_010",
        "subreddit": "lawyers",
        "title": "Will AI replace paralegals in the next 5 years?",
        "body_text": "Our paralegals already manage AI outputs and QA them. I think roles shift rather than disappear. Firms that use AI will need people who understand both workflow and model limits. Associates who ignore AI will be replaced by associates who don't.",
        "author": "employment_lawyer",
        "score": 178,
        "num_comments": 96,
        "created_date": "2025-03-01",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_paralegal_future/",
        "post_type": "post",
    },
    {
        "id": "reddit_011",
        "subreddit": "LegalTech",
        "title": "",
        "body_text": "Skeptical of the hype cycle. Half the legal AI products feel like marketing vaporware. Show me audit logs, citation grounding, and error rates on my practice area before I ask partners to sign a three year contract.",
        "author": "skeptical_gc",
        "score": 112,
        "num_comments": 0,
        "created_date": "2025-03-02",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_paralegal_future/",
        "post_type": "comment",
    },
    {
        "id": "reddit_012",
        "subreddit": "LawFirm",
        "title": "State bar AI disclosure rules — what is your firm doing?",
        "body_text": "Pennsylvania now expects disclosure when AI drafts court submissions. We are building a red yellow green use policy and quarterly governance review. Competence duty means understanding limitations of whatever tool you use, not becoming an ML engineer.",
        "author": "risk_partner",
        "score": 88,
        "num_comments": 34,
        "created_date": "2025-04-18",
        "source_url": "https://www.reddit.com/r/LawFirm/comments/sample_bar_ai_policy/",
        "post_type": "post",
    },
    {
        "id": "reddit_013",
        "subreddit": "lawyers",
        "title": "Clio AI features — worth it for small firm?",
        "body_text": "Three attorney PI shop considering Clio Work with Vincent AI. Monthly cost adds up but if it saves drafting time on demand letters might pay off. Anyone compare it to just using Claude with firm templates?",
        "author": "pi_attorney",
        "score": 54,
        "num_comments": 27,
        "created_date": "2025-05-06",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_clio_ai/",
        "post_type": "post",
    },
    {
        "id": "reddit_014",
        "subreddit": "LegalTech",
        "title": "Document review AI is useful; legal reasoning AI is not ready",
        "body_text": "In my experience AI excels at sorting, summarizing, and surfacing responsive documents. It struggles with gray area legal judgment and novel questions. Treat it as a workflow accelerator with mandatory human oversight.",
        "author": "litigation_consultant",
        "score": 203,
        "num_comments": 41,
        "created_date": "2024-12-03",
        "source_url": "https://www.reddit.com/r/LegalTech/comments/sample_review_vs_reasoning/",
        "post_type": "post",
    },
    {
        "id": "reddit_015",
        "subreddit": "lawyers",
        "title": "",
        "body_text": "Client confidentiality keeps us on firm-approved tools only. Uploading sensitive files to random chatbots is reckless. Need vendors that contractually promise no training on our data.",
        "author": "privacy_focused",
        "score": 145,
        "num_comments": 0,
        "created_date": "2024-12-04",
        "source_url": "https://www.reddit.com/r/LegalTech/comments/sample_review_vs_reasoning/",
        "post_type": "comment",
    },
    {
        "id": "reddit_016",
        "subreddit": "ChatGPT",
        "title": "Used GPT for contract redlines — fast but missed indemnity nuance",
        "body_text": "I tried it on a vendor agreement. Got a decent first markup in minutes but missed a subtle indemnity carve-out that mattered. Useful for speed, dangerous if you skip line-by-line review. Pros and cons depending on document complexity.",
        "author": "inhouse_counsel",
        "score": 76,
        "num_comments": 22,
        "created_date": "2024-08-22",
        "source_url": "https://www.reddit.com/r/ChatGPT/comments/sample_contract_redlines/",
        "post_type": "post",
    },
    {
        "id": "reddit_017",
        "subreddit": "LegalTech",
        "title": "Lexis+ AI hallucination rate — anyone benchmarking?",
        "body_text": "Seeing studies cite roughly one in six bad queries for some legal AI products. We run spot checks on every research memo draft. Trust but verify is the only sustainable workflow.",
        "author": "research_librarian",
        "score": 129,
        "num_comments": 38,
        "created_date": "2025-01-28",
        "source_url": "https://www.reddit.com/r/LegalTech/comments/sample_lexis_benchmark/",
        "post_type": "post",
    },
    {
        "id": "reddit_018",
        "subreddit": "LawFirm",
        "title": "Flat fee migration partly driven by AI efficiency",
        "body_text": "We moved several discovery-heavy matters to flat fees after AI assisted review cut our hours. Margins improved but only because we tracked time saved and repriced deliberately. Billable hour firms may resist even when tools work.",
        "author": "managing_partner_sm",
        "score": 91,
        "num_comments": 18,
        "created_date": "2025-02-19",
        "source_url": "https://www.reddit.com/r/LawFirm/comments/sample_flat_fee_ai/",
        "post_type": "post",
    },
    {
        "id": "reddit_019",
        "subreddit": "lawyers",
        "title": "Law student — should I learn prompting or Westlaw first?",
        "body_text": "Career services says AI literacy matters but clinics still grade on traditional research. Feels like the bar exam world and the practice world are diverging. What skills actually matter for a 2026 associate?",
        "author": "3L_student",
        "score": 167,
        "num_comments": 84,
        "created_date": "2025-04-02",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_law_student_ai/",
        "post_type": "post",
    },
    {
        "id": "reddit_020",
        "subreddit": "LegalTech",
        "title": "",
        "body_text": "Integration beats shiny demos. If AI does not plug into DMS, billing, and ethical walls it dies in pilot purgatory. Vendors underestimate change management.",
        "author": "legal_ops",
        "score": 84,
        "num_comments": 0,
        "created_date": "2025-04-03",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_law_student_ai/",
        "post_type": "comment",
    },
    {
        "id": "reddit_021",
        "subreddit": "lawyers",
        "title": "AI governance board — what should it actually review?",
        "body_text": "AmLaw firm stood up an AI committee. We review vendor DPAs, log retention, hallucination incident reports, and training materials. Still figuring out what competence looks like for partners vs associates.",
        "author": "innovation_counsel",
        "score": 62,
        "num_comments": 15,
        "created_date": "2025-05-20",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_governance_board/",
        "post_type": "post",
    },
    {
        "id": "reddit_022",
        "subreddit": "ChatGPT",
        "title": "",
        "body_text": "The black box problem is real. Lawyers need to see sources and reasoning paths. Until then adoption at serious firms stays cautious regardless of hype.",
        "author": "tech_savvy_attorney",
        "score": 198,
        "num_comments": 0,
        "created_date": "2025-05-21",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_governance_board/",
        "post_type": "comment",
    },
    {
        "id": "reddit_023",
        "subreddit": "LegalTech",
        "title": "Spellbook vs generic GPT for contract drafting?",
        "body_text": "Testing Spellbook on NDAs and MSAs. Better guardrails than raw ChatGPT but still not signing outputs without review. Game changer for first drafts if your firm accepts the subscription cost.",
        "author": "startup_counsel",
        "score": 73,
        "num_comments": 29,
        "created_date": "2024-10-11",
        "source_url": "https://www.reddit.com/r/LegalTech/comments/sample_spellbook/",
        "post_type": "post",
    },
    {
        "id": "reddit_024",
        "subreddit": "LawFirm",
        "title": "Paralegal team now QA-ing all AI-generated drafts",
        "body_text": "We did not cut paralegal headcount. We redirected them to verification workflows and client-ready formatting. AI handles volume; humans handle accountability. That seems to be the sustainable model.",
        "author": "office_manager",
        "score": 118,
        "num_comments": 31,
        "created_date": "2025-03-14",
        "source_url": "https://www.reddit.com/r/LawFirm/comments/sample_paralegal_qa/",
        "post_type": "post",
    },
    {
        "id": "reddit_025",
        "subreddit": "lawyers",
        "title": "Has anyone been sanctioned for AI use besides Mata?",
        "body_text": "Collecting examples for a CLE on competence. Looking for cases where courts flagged unverified AI citations or disclosure failures. Human researcher still has to validate the list ironically.",
        "author": "cle_speaker",
        "score": 95,
        "num_comments": 47,
        "created_date": "2025-06-01",
        "source_url": "https://www.reddit.com/r/lawyers/comments/sample_sanctions_examples/",
        "post_type": "post",
    },
]
